### ISSUE TITLE
A query about pinned dependencies for spec-power-model when using this repo

### ISSUE THREAD

**Issue by mrchrisadams** [green-coding-solutions/eco-server-energy-estimation#2]
Hi folks

I tried using this to figure out the underlying tooling on a couple of servers, and 'Ive seen this issue when installing. Is there a required version of python needed?

I ran this on a machine using python 3.8.10. This is an old python but not quite end of life (yet).

This was also installing into a new virtual environment, as per the installer in this repo:

https://github.com/green-coding-solutions/eco-server-energy-estimation/blob/main/xgb/install.sh#L60-L62

Here's the error message I see:

```
Creating a virtual environment...
ERROR: Could not find a version that satisfies the requirement numpy==1.26.4 (from -r requirements.txt (line 1)) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4)
```

I can try running this on a fresh machine with a newer python, but I figured it might help to ask here first.

**Comment by ArneTR** [comment]
This error we have also seen in Ubuntu 20.04 Github Runners.

It is as you said: Python 3.8 is too old and numpy has dropped support for it.

Technically we do not depend on numpy 1.26.4 but have just followed along with dependabots security update PRs that we were getting.

Can you upgrade to Python 3.10 ? Otherwise feel free to downgrade dependecies in the requirements.txt until it works for you and submit a PR. We will give it a look if all functionality is still good.

**Comment by mrchrisadams** [comment]
Thanks Arne! I've been meaning to upgrade to a newer python on that box for ages, and there are perf benefits anyway, so I'll try it out and report back

**Comment by ribalba** [comment]
@mrchrisadams has this been resolved?

**Comment by mrchrisadams** [comment]
Yeah, we're using a less old-and-busted version of python.

There's some more discussion here, but this is totally ok to close. thanks for checking

https://github.com/green-coding-solutions/cloud-energy/issues/43
